apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: graph
  namespace: grafana
spec:
  config:
    log:
      mode: console
      level: warn
    security:
      admin_user: root
      admin_password: local
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
  - matchExpressions:
    - { key: app, operator: In, values: [grafana] }
  resources:
    limits:
      cpu: 2000m
      memory: 8000Mi
    requests:
      cpu: 100m
      memory: 200Mi
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
  namespace: grafana
spec:
  name: middleware.yaml
  datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://db.prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"
